extends:
  - "@commitlint/config-conventional"
rules:
  # Scope enum should be customized to match project needs
  scope-enum:
    - 2
    - always
    - - ci
  # Type enum should be consistent across data science projects
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - refactor
      - revert
      - style
      - version
