version: "3.9"

services:
  client-pip:
    profiles:
      - e2e
    restart: unless-stopped
    build:
      args:
        TARGET_PYTHON_VERSION: $(TARGET_PYTHON_VERSION)
      dockerfile_inline: |
        ARG TARGET_PYTHON_VERSION 
        FROM python:$TARGET_PYTHON_VERSION
        COPY config.ini config.ini
        COPY /dist/ /dist
        RUN pip install /dist/hass_inspirair*.whl
        ENV HI_MQTT_HOST=mqtt \
            HI_MODBUS_CLIENT=hass_inspirair.modbus.client.get_async_tcp_client \ 
            HI_MODBUS_TCP_HOST=modbus \
            HI_MODBUS_TCP_PORT=5020 
        CMD python -m hass_inspirair
  client:
    restart: unless-stopped
    build:
      dockerfile_inline: |
        FROM python:3.9 as build
        RUN pip install poetry
        COPY poetry.lock pyproject.toml .
        RUN poetry install
        COPY . .
        RUN poetry build
        FROM python:3.9 
        COPY --from=build /dist/ /dist
        RUN pip install /dist/hass_inspirair*.whl
        CMD python -m hass_inspirair
    environment:
      - HI_MQTT_HOST=mqtt
      - HI_MODBUS_CLIENT=hass_inspirair.modbus.client.get_async_tcp_client
      - HI_MODBUS_TCP_HOST=modbus
      - HI_MODBUS_TCP_PORT=5020
  modbus:
    build:
      dockerfile_inline: |
        FROM python:3.10
        RUN pip install pymodbus aiohttp
        COPY tests/modbus/setup.json setup.json
        CMD pymodbus.simulator --json_file setup.json --log debug
    ports:
      - "8081:8081"
      - "5020:5020"

  mqtt:
    build:
      dockerfile_inline: |
        FROM eclipse-mosquitto
        RUN echo -e "listener 1883\nallow_anonymous true\n" > /mosquitto/config/mosquitto.conf

    ports:
      - "1883:1883"
      - "9001:9001"

  home-assistant:
    image: homeassistant/home-assistant
    stop_grace_period: 5m
    ports:
      - "8123:8123"
    volumes:
      - config:/config

volumes:
  config: {}
