name: 🚀 Tag & Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v5
      - name: Poetry install
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load virtual environment cache
        id: cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install
      - name: Update project version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global --add safe.directory $(pwd)
          poetry version $(poetry run semantic-release -c .github/workflows/release.ini version --print)
          git add pyproject.toml

      - name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.PAT}}
        run: |
          poetry run semantic-release -c .github/workflows/release.ini version
